### ISSUE TITLE
Support self-signed certificates

### ISSUE THREAD

**Issue by gdetrez** [zachlatta/postman#18]
I have a SMTP server with a self signed certificate. Right now, postman just stops with the error `x509: certificate signed by unknown authority`. Maybe an option to specify the certificate fingerprint?

Thanks for a useful little tool!

**Comment by gdetrez** [comment]
I looked a bit in the documentation and it seems that the TLS library
doesn't expose a way to pass the expected certificate fingerprint. (But I'm
new to go so I might have missed it.) Apparently the only way is to disable
certificate checking entirely (using InsecureSkipVerify) which isn't really
what I would like...
I'll keep using the work around for now I guess :-)

On Mon, Dec 15, 2014 at 11:05 PM, Zach Latta <notifications@github.com>
wrote:

>
> Love this idea!
>
> Definitely agree that this would be useful - I ran my own SMTP serve for
> a while that used a self-signed cert.
>
> I have my hands pretty full right now, a PR would be welcome!
>
> As a temporary workaround, you can add the certificate to your system's
> trusted certs and it should work. See
>
> http://kb.kerio.com/product/kerio-connect/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html.
>
>
> --
> Zach Latta http://zachlatta.com https://github.com/zachlatta
> https://twitter.com/zachlatta
>
>
> On Mon, Dec 15, 2014, at 11:57 AM, Grégoire Détrez wrote:
> > I have a SMTP server with a self signed certificate. Right now,
> > postman just stops with the error x509: certificate signed by unknown
> > authority. Maybe an option to specify the certificate fingerprint?
>
>
> > Thanks for a useful little tool!
>
>
> > — Reply to this email directly or view it on GitHub[1].
>
> >
>
>
>
> Links:
>
> 1. https://github.com/zachlatta/postman/issues/18
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/postman/issues/18#issuecomment-67075094>.
>



-- 
ǵ

**Comment by zachlatta** [comment]
Closing for now due to this being a limitation in the TLS library. @gdetrez if you know  of an alternative, let me know!
