### ISSUE TITLE
Letters with accents on the subject field

### ISSUE THREAD

**Issue by nicolasguzca** [zachlatta/postman#19]
I have notice when I try to send an email with a subject that has an accent ( qué, porqué, etc) it removes the letter.

I tried putting the accents like this &aacute and still had no luck

**Comment by zachlatta** [comment]
Hmm, odd. Also ran into similar issues sending to emails with accents in
them (ex. "Andrew Péna <apena@example.com>").

Not entirely sure what might be causing this, probably the email library
we're using or Go's built-in library (the latter would surprise me).

**Comment by zachlatta** [comment]
@jordan-wright any thoughts on this?

**Comment by zachlatta** [comment]
@jordan-wright ping?

**Comment by jordan-wright** [comment]
Whoa- my apologies, this notification slipped past me.

I think I've seen something like this before. I don't think we currently do anything in the way of unicode support in the subject line, or headers, which is probably what's causing this.

Let me go look at the RFC's to see the best way to handle this and work on adjustments to my library.

**Comment by zachlatta** [comment]
Sounds good – let me know if you find anything.

**Comment by jordan-wright** [comment]
Created [email/#22](https://github.com/jordan-wright/email/issues/22). Looks like there is quite a bit of work to get this working correctly, so it'll take a bit of time. I'll keep that issue updated.

**Comment by nicolasguzca** [comment]
Thank you very much guys for the help!

**Comment by zachlatta** [comment]
@nicolasguzca seems like this should be fixed, now that jordan-wright/email#22 has been. Can you try again and let us know how it goes?

**Comment by nicolasguzca** [comment]
Sure thing, I will test it this afternoon and I'll let you guys know. Thanks @zachlatta and @jordan-wright you guys rock!

**Comment by jordan-wright** [comment]
@zachlatta, I would suggest changing the version of ```email``` in use to the gopkg versioned instance to provide backwards compatibility. Specifically, I would use v1.1 (gopkg.in/jordan-wright/email.v1), since version 2 (the current version) is only compatible with Go version >= 1.5 due to the change to use the ```mime/quotedprintable``` package introduced in the stdlib.
