### ISSUE TITLE
I can't change to the body tab? what gives?

### ISSUE THREAD

**Issue by joshbedo** [zachlatta/postman#20]
I'm trying to simply change to the body tab and can't? Is their something i have to do first? I couldn't find anything in the documentation.

**Comment by zachlatta** [comment]
What do you mean by "body tab"?

On Wed, Aug 12, 2015 at 3:24 PM, Josh Bedo <notifications@github.com> wrote:

> I'm trying to simply change to the body tab and can't? Is their something
> i have to do first? I couldn't find anything in the documentation and this
> new interface is bogus.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/postman/issues/20>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by joshbedo** [comment]
The body parameters tab 
![](http://content.screencast.com/users/joshbedo/folders/Jing/media/d87a8ce7-5e34-42cf-a8ed-ae035106b9d6/2015-08-13_0825.png)

**Comment by zachlatta** [comment]
Ah, I think you may want to file this issue in
https://github.com/postmanlabs/postman-app-support instead. This repo is
for the mail merge tool.

On Thu, Aug 13, 2015 at 5:33 AM, Josh Bedo <notifications@github.com> wrote:

> The body parameters tab
>
> <https://camo.githubusercontent.com/81f4911bb91d2821f7c2e94fe5b26ed2cb2c4915/687474703a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f6a6f73686265646f2f666f6c646572732f4a696e672f6d656469612f64383761386365372d356533342d343263662d613865642d6165303335313036623964362f323031352d30382d31335f303832352e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/postman/issues/20#issuecomment-130652159>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta

**Comment by joshbedo** [comment]
Got it, sorry about that created an issue on that repo.

**Comment by zachlatta** [comment]
No worries! Glad we got it figured out.

On Fri, Aug 14, 2015 at 1:33 AM, Josh Bedo <notifications@github.com> wrote:

> Got it, sorry about that created an issue on that repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zachlatta/postman/issues/20#issuecomment-131024261>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
